"use client"

import { Inter } from "next/font/google";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";
import { useState } from "react";


//const inter = new Inter({ subsets: ["latin"] });

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    const [isSidebarOpen, setSidebarOpen] = useState(false);

    const toggleSidebar = () => {
      //  console.log('sdsdsd')
        setSidebarOpen(!isSidebarOpen);
    };
    const SidebarClose = () => {
        //  console.log('sdsdsd')
          setSidebarOpen(false);
      };

    return (
        <>
              <div className="w-full flex flex-col  bg-[#151C2D] text-white">
              <Navbar toggleSidebar={toggleSidebar} />
                
                <div className="flex ">
                  
                   
                   <Sidebar isSidebarOpen={isSidebarOpen} toggleSidebar={SidebarClose} />
                  
                    <div className={`min-h-screen md:flex-grow  ${isSidebarOpen ? 'hidden w-0' : 'flex-grow'}`}>
                    {children}
                    </div>
                   
                </div>
            </div>
        </>
    );
}
